<a href="https://colab.research.google.com/github/sukanyaganik14-collab/practice/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PANDAS IN PYTHON

In [42]:
import pandas as pd

In [43]:
pd.__version__

'2.2.2'

In [44]:
list_s = [1,2,-6,8.9,'data values']
print(list_s)

[1, 2, -6, 8.9, 'data values']

In [45]:
series1 = pd.Series(list_s)
print(series1)

0              1
1              2
2             -6
3            8.9
4    data values
dtype: object

In [46]:
type(series1)

pandas.core.series.Series

In [47]:
series2 = pd.Series([1,2,3,4])
print(series2)

0    1
1    2
2    3
3    4
dtype: int64

In [48]:
empty_s = pd.Series([])
print(empty_s)

Series([], dtype: object)

assigning index

In [49]:
series3 = pd.Series([1,2,3,4], index = ['a','b','c','d'])
print(series3)

a    1
b    2
c    3
d    4
dtype: int64

declaring a datatype

In [50]:
series4 = pd.Series([5,6,7,8], index =['e','f','g','h'], dtype = float)
print(series4)

e    5.0
f    6.0
g    7.0
h    8.0
dtype: float64

giving a column name

In [51]:
series5 = pd.Series([73,74,76],index = ['suchi','sukanya','barsha'], name= 'roll numbers')
print(series5)

suchi      73
sukanya    74
barsha     76
Name: roll numbers, dtype: int64

for declaring single (scalar) values

In [52]:
scalar_s = pd.Series(0.5)
print(scalar_s)

0    0.5
dtype: float64

for declaring same value for different index

In [53]:
scalar_s = pd.Series('mca', index =['suchi','sukanya','barsha'])
print(scalar_s)

suchi      mca
sukanya    mca
barsha     mca
dtype: object

create from dictionary

In [54]:
dict_s = pd.Series({'a':1, 'b':2})
print(dict_s)

a    1
b    2
dtype: int64

# operators

In [55]:
s6 = pd.Series([1,2,3,4,5,6])
print(s6)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

to access the value

In [56]:
s6[0]

np.int64(1)

In [57]:
s6[4]

np.int64(5)

slicing values by using index

In [58]:
s6[0:4]

0    1
1    2
2    3
3    4
dtype: int64

max and min function

In [59]:
print(max(s6))
print(min(s6))

6
1

In [60]:
s6[s6 > 2]

2    3
3    4
4    5
5    6
dtype: int64

In [61]:
s6

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [62]:
s7 = pd.Series([1,2,3,4,5,6])
print(s7)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [63]:
s6

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [64]:
s7

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

adding two series

In [65]:
s6+s7

0     2
1     4
2     6
3     8
4    10
5    12
dtype: int64

In [66]:
s5 = pd.Series([1,2,3])
print(s5)

0    1
1    2
2    3
dtype: int64

adding unequal data (it handles missing data)

In [67]:
s5 + s6

0    2.0
1    4.0
2    6.0
3    NaN
4    NaN
5    NaN
dtype: float64

subtracting two series

In [68]:
s6-s7

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

# DATA FRAMES IN PANDAS

how to create a dataframe

In [69]:
import pandas as pd

empty dataframe

In [70]:
empty_df = pd.DataFrame()
print(empty_df)

Empty DataFrame
Columns: []
Index: []

creating dataframe using list

In [71]:
lst = ['sukanya','suchitra','barsha']
print(lst)

['sukanya', 'suchitra', 'barsha']

creating dataframe using the above creates list

In [72]:
df1 = pd.DataFrame(lst)
print(df1)

          0
0   sukanya
1  suchitra
2    barsha

In [73]:
df1

          0
0   sukanya
1  suchitra
2    barsha

In [86]:
lst1 = ['ihcus','aynakus','ahsrab']
print(lst1)

['ihcus', 'aynakus', 'ahsrab']

In [87]:
df2 = pd.DataFrame(lst1)
print(df2)

         0
0    ihcus
1  aynakus
2   ahsrab

In [74]:
lst_of_lst =[[1,2,3],[2,3,4],[4,5,6]]
print(lst_of_lst)

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]

In [75]:
df2 = pd.DataFrame(lst_of_lst)
print(df2)

   0  1  2
0  1  2  3
1  2  3  4
2  4  5  6

creating a dictionary

array values should be of same length

In [76]:
dict1 = {'ID':[11,22,33,44],'SN':[1,2,3,4]}
print(dict1)

{'ID': [11, 22, 33, 44], 'SN': [1, 2, 3, 4]}

In [77]:
df3 = pd.DataFrame(dict1)
print(df3)

   ID  SN
0  11   1
1  22   2
2  33   3
3  44   4

creating list of dictionaries

In [78]:
ls_dict = [{'a':1, 'b':2},{'a':3, 'b':4}]
df5 = pd.DataFrame(ls_dict)
df5

   a  b
0  1  2
1  3  4

creating list of dictionaries by using dataframes

In [79]:
ls_dict = [{'a':1, 'b':2},{'a':3, 'b':4, 'c':5}]
df5 = pd.DataFrame(ls_dict)
df5

   a  b    c
0  1  2  NaN
1  3  4  5.0

In [84]:
ls_dict = [{'a':3, 'b':4},{'a':6, 'b':7, 'c':8}]
df6 = pd.DataFrame(ls_dict)
df6

   a  b    c
0  3  4  NaN
1  6  7  8.0

creating dictionaries of series with the help of dataframes

In [80]:
dict_sr = {'id': pd.Series([1,2,3]), 'sn':pd.Series([111,222,333])}
df6 = pd.DataFrame(dict_sr)
df6

   id   sn
0   1  111
1   2  222
2   3  333

In [83]:
dict_ser = {'id': pd.Series([1,2,3]), 'sn':pd.Series([101,202,303])}
df7 = pd.DataFrame(dict_ser)
df7

   id   sn
0   1  101
1   2  202
2   3  303